#!/usr/bin/env bash
# Gives information about the dhkschool file

if [ -e "dhkschool" ]; then
    echo "dhkschool file exists"
    if [ -s "dhkschool" ]; then
	echo "dhkschool file is not empty"
    else
	echo "dhkschool file is empty"
    fi

    if [ -f "dhkschool" ]; then
	echo "dhkschool is a regular file"
    fi

else
    echo "dhkschool file does not exist"

fi
